### ISSUE TITLE
"certificate verify failed" for post_cutout  on  dev.neurodata.io

### ISSUE THREAD

**Issue by kkutten1** [openconnectome/ndio#275]
| ndio version |  os  | python |
|-----|------|-------|
| 1.1.6  | Ubuntu 14.04    | 2.7.6    |

@Aeusman @kunallillaney 
- Steps to reproduce
```
import ndio.remote.neurodata as neurodata
import numpy
nd = neurodata(hostname="dev.neurodata.io", user_token="myUserToken")
array = numpy.ones([10,10,10])
nd.post_cutout("myToken", "test", 0, 0, 0, data=array, resolution=0)
```
- Result
```
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./postCutoutFail.py", line 11, in <module>
    nd.post_cutout("ara3", "test", 0, 0, 0, data=array, resolution=0)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 99, in wrapped
    return f(self, *args, **kwargs)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 857, in post_cutout
    resolution)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 926, in _post_cutout_no_chunking_blosc
    req = requests.post(url, data=blosc_data, headers={'Content-Type': 'application/octet-stream'})
  File "~/.local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)                                                                                                                                             
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed  
```

**Comment by kkutten1** [comment]
As of this morning the "certificate verify failed" error has disappeared.  I now receive a 'Timestamp is not None for Image Channels.' error.  This is strange since channel "test" is of type image.
```
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./postCutoutFail.py", line 11, in <module>
    nd.post_cutout("ara3", "test", 0, 0, 0, data=array, resolution=0)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 99, in wrapped
    return f(self, *args, **kwargs)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 857, in post_cutout
    resolution)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 932, in _post_cutout_no_chunking_blosc
    raise RemoteDataUploadError(req.text)
ndio.remote.errors.RemoteDataUploadError: POST transaction rollback. 'Timestamp is not None for Image Channels.'
```

**Comment by kunallillaney** [comment]
@kkutten1 How did the certificate error disappear? Did you update your system?

**Comment by kunallillaney** [comment]
@kkutten1 The error you get now seems like a bug in ndio for project and channel creation. You will have to delete the old one and create them again via ndio.
@Aeusman Was the s3_backend fix pushed to master on github?

**Comment by kkutten1** [comment]
@kunallillaney: I have no idea how the error disappeared.  I did not change anything

**Comment by kkutten1** [comment]
@kunallillaney Creating a channel through ndio or the Admin Console doesn't resolve this issue
```
import ndio.remote.neurodata as neurodata
import numpy

# Create Channel
token = "ara3"
dataset = "ara3"
channel = "test"
nd = neurodata(hostname="dev.neurodata.io", user_token="myUserToken")
nd.create_channel(channel, token, dataset, "image", "float32", 0, 0, False)

# Post cutout
array = numpy.ones([10,10,10])
nd.post_cutout("ara3", channel, 0, 0, 0, data=array, resolution=0)
```

```
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
~/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./postCutoutFail.py", line 18, in <module>
    nd.post_cutout("ara3", channel, 0, 0, 0, data=array, resolution=0)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 99, in wrapped
    return f(self, *args, **kwargs)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 857, in post_cutout
    resolution)
  File "/cis/project/clarity/code/ndio/ndio/remote/neurodata.py", line 932, in _post_cutout_no_chunking_blosc
    raise RemoteDataUploadError(req.text)
ndio.remote.errors.RemoteDataUploadError: POST transaction rollback. 'Timestamp is not None for Image Channels.'
```

**Comment by kunallillaney** [comment]
@kkutten1 I am not sure if the fix was pushed to ndio or not. Let's wait for confirmation from @Aeusman.

**Comment by Aeusman** [comment]
The S3 default change has not been pushed, that said this: nd.create_channel(channel, token, dataset, "image", "float32", 0, 0, False) indicates that it should have been created with that flag set to 0.

**Comment by kunallillaney** [comment]
@Aeusman Every project in the database is marked as sebackend=True.

**Comment by kunallillaney** [comment]
@kkutten1 This was fixed with you.
